import argparse
import csv
import logging
import sched
import threading
import time
from datetime import datetime
from pathlib import Path

import open_lambda_api as ol
from generate_plan import PLANS_DIRECTORY_DEFAULT
from helper.common import init_logging, parse_response, CONFIG

init_logging()

logger = logging.getLogger(__name__)

OPENLAMBDA_RESULTS = []
OPENLAMBDA_RESULTS_LOCK = threading.Lock()

"""
Load the workload plan from a CSV file generated by the workload generator
:param plan_id: ID of the plan to load
:param plan_dir: Directory where the plans are stored
"""


def load_plan(plan_id: int, plan_dir: str = PLANS_DIRECTORY_DEFAULT) -> list:
    requests = []
    path = Path(plan_dir) / f"plan{plan_id}.csv"
    with open(path, "r") as f:
        csv_reader = csv.reader(f)

        for index, row in enumerate(csv_reader):
            iat = float(row[0])
            deployment_id = float(row[1])
            exec_duration = float(row[2])
            function_name = row[3]
            parameter_value = int(row[4])
            parameter_name = CONFIG[function_name]["parameterName"]
            request = {
                "iat": iat,
                "data": {
                    "deploymentId": deployment_id,
                    "index": index,
                    "duration": exec_duration,
                    "functionName": function_name,
                    parameter_name: parameter_value,
                },
            }
            requests.append(request)

    return requests


"""
Execute the workload plan
:param plan_id: id of the plan to use
returns: filename of the results CSV
"""


def execute_plan(
        plan_id: int,
        out_dir: str = "results",
        plan_dir: str = PLANS_DIRECTORY_DEFAULT,
        scaling: float = 1.0,
):
    # set results to empty list
    with OPENLAMBDA_RESULTS_LOCK:
        OPENLAMBDA_RESULTS.clear()

    logger.info(f"Executing plan {plan_id}")
    requests = load_plan(plan_id, plan_dir)

    if not ol.is_running():
        raise Exception("OpenLambda is not reachable")

    threads = []  # keep track so that we can join them later

    s = sched.scheduler(time.time, time.sleep)

    # Register scheduler events
    logger.info("Registering events at scheduler")
    for index, request in enumerate(requests):
        iat = request["iat"] * scaling
        deployment_id = request["data"]["deploymentId"]
        function_name = request["data"]["functionName"]
        parameter_name = CONFIG[function_name]["parameterName"]
        parameter_value = request["data"][parameter_name]
        payload = CONFIG[function_name]["jsonPayload"].copy()
        payload[parameter_name] = parameter_value

        arguments = (threads, index, deployment_id, function_name, payload)
        s.enter(delay=iat, priority=1, action=start_request_thread, argument=arguments)

    # run scheduler
    logger.info("Starting scheduler")
    s.run()

    # case: scheduler started threads, which are still runnning
    # -> wait for all threads to finish
    logger.info("Waiting until all threads completed")
    for t in threads:
        t.join()

    logger.info("ExecutePlan finished now")

    # store results
    filename = f"{datetime.now()}_{plan_id}.csv"
    path = Path(out_dir) / filename
    logger.info(f"Saving results to {path.absolute()}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("requestIndex,execDuration,startTimestamp,endTimestamp\n")
        f.writelines(OPENLAMBDA_RESULTS)

    return filename


"""
Starts a new thread to handle the request to OpenLambda
:param threads: reference to global list of threads
:param index: index of the request in the plan
:param function_name: name of the function to call
:param payload: payload data to send with the function call
"""


def start_request_thread(
        threads: list, index: int, deployment_id: int, function_name: str, payload: dict
):
    t = threading.Thread(
        target=_send_request, args=(index, deployment_id, function_name, payload)
    )

    # keep track of started threads
    threads.append(t)

    t.start()


"""
Send Request to OpenLambda
:param index: index of the request in the plan
:param request: request data

"""


def _send_request(index, deployment_id, function_name, payload) -> None:
    logger.info(f"Executing {index}th request")
    response = ol.run_function(function_name, payload, index, deployment_id)

    if response is None:
        logger.error(f"Failed to execute {index}th request")
        with OPENLAMBDA_RESULTS_LOCK:
            OPENLAMBDA_RESULTS.append(f"{index},,,\n")
        return

    # extract results
    latency, timestamps = parse_response(function_name, response)
    start_timestamp = timestamps["starting_time"]
    end_timestamp = timestamps["finishing_time"]

    # save results
    with OPENLAMBDA_RESULTS_LOCK:
        OPENLAMBDA_RESULTS.append(
            f"{index},{latency},{start_timestamp},{end_timestamp}\n"
        )


if __name__ == "__main__":
    # cli parsing
    parser = argparse.ArgumentParser(description="Execute workload plans")
    parser.add_argument("--plan-id", type=int, help="ID of the plan to execute")
    parser.add_argument(
        "--num-plans",
        type=int,
        help="Number of plans used during generation. Executes all plans",
    )
    parser.add_argument(
        "--plan-dir",
        type=str,
        default=PLANS_DIRECTORY_DEFAULT,
        help="Directory where the plans are stored",
    )
    parser.add_argument(
        "--out-dir",
        type=str,
        default="results",
        help="Directory where the results should be stored",
    )
    parser.add_argument(
        "--scaling",
        type=float,
        default=1.0,
        help="IAT of plan are multiplied by this value",
    )
    args = parser.parse_args()
    plan_id = args.plan_id
    num_plans = args.num_plans
    plan_dir = args.plan_dir
    out_dir = args.out_dir
    scaling = args.scaling

    if plan_id is not None:
        execute_plan(plan_id, out_dir, plan_dir, scaling)
        exit(0)

    assert (num_plans is not None and num_plans > 0)

    for plan_id in range(num_plans):
        execute_plan(plan_id, out_dir, plan_dir, scaling)
